CREATE TABLE "doc_articles" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_doc_articles_by_slug" ON "doc_articles" ("slug");
CREATE TABLE "releases" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "version" TEXT NOT NULL,
    "channel" TEXT NOT NULL,
    "released_on" TEXT NOT NULL,
    "size_mb" TEXT NOT NULL,
    "signature_prefix" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "notes" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE "issues" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "key" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "component" TEXT NOT NULL,
    "severity" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "organization_id" BIGINT NOT NULL,
    "details" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE "auth_sessions" (
    "token_hash" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    PRIMARY KEY ("token_hash")
);
CREATE INDEX "index_auth_sessions_by_user_id" ON "auth_sessions" ("user_id");
CREATE TABLE "users" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" TEXT NOT NULL,
    "display_name" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_users_by_email" ON "users" ("email");
CREATE TABLE "organizations" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "vat" TEXT NOT NULL,
    "plan_label" TEXT NOT NULL,
    "supported_builds" TEXT NOT NULL,
    "lts_subscriptions" INTEGER NOT NULL,
    "industrial_lts_subscriptions" INTEGER NOT NULL,
    "technical_contact" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_organizations_by_slug" ON "organizations" ("slug");
CREATE TABLE "memberships" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" BIGINT NOT NULL,
    "organization_id" BIGINT NOT NULL,
    "role" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_memberships_by_user_id" ON "memberships" ("user_id");
CREATE INDEX "index_memberships_by_organization_id" ON "memberships" ("organization_id");
