ALTER TABLE "issues" ADD COLUMN "created_at" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "issues" ADD COLUMN "opened_by_user_id" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "issues" ADD COLUMN "updated_at" BIGINT NOT NULL DEFAULT 0;
CREATE TABLE "issue_comments" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "issue_id" BIGINT NOT NULL,
    "author_user_id" BIGINT NOT NULL,
    "author_role" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_issue_comments_by_issue_id" ON "issue_comments" ("issue_id");
