CREATE TABLE "ephemeral_downloads" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "token" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "organization_id" BIGINT NOT NULL,
    "release_version" TEXT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    "created_at" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_ephemeral_downloads_by_token" ON "ephemeral_downloads" ("token");
CREATE INDEX "index_ephemeral_downloads_by_user_id" ON "ephemeral_downloads" ("user_id");
CREATE INDEX "index_ephemeral_downloads_by_organization_id" ON "ephemeral_downloads" ("organization_id");
