-- Unified blob metadata (sole SoT for digests / sizes). Digests leave Release.
CREATE TABLE "storage_objects" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "scope" TEXT NOT NULL,
    "object_key" TEXT NOT NULL,
    "organization_id" BIGINT NOT NULL,
    "sha256" TEXT NOT NULL,
    "size_bytes" BIGINT NOT NULL,
    "content_type" TEXT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "updated_at" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_storage_objects_by_scope_and_object_key" ON "storage_objects" ("scope", "object_key");
CREATE INDEX "index_storage_objects_by_organization_id" ON "storage_objects" ("organization_id");

-- Backfill real digests from catalog (skip pending / non-hex).
INSERT INTO "storage_objects" (
    "scope",
    "object_key",
    "organization_id",
    "sha256",
    "size_bytes",
    "content_type",
    "created_at",
    "updated_at"
)
SELECT
    'release',
    "id"::text,
    0,
    lower("sha256"),
    GREATEST(
        1,
        ROUND(NULLIF("size_mb", '')::double precision * 1048576)::bigint
    ),
    '',
    EXTRACT(EPOCH FROM NOW())::bigint,
    EXTRACT(EPOCH FROM NOW())::bigint
FROM "releases"
WHERE length("sha256") = 64
  AND "sha256" ~ '^[0-9a-fA-F]{64}$'
  AND "size_mb" ~ '^[0-9]+(\.[0-9]+)?$';

ALTER TABLE "releases" DROP COLUMN "size_mb";
ALTER TABLE "releases" DROP COLUMN "sha256";
