CREATE TABLE "issue_attachments" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "issue_id" BIGINT NOT NULL,
    "organization_id" BIGINT NOT NULL,
    "image_id" TEXT NOT NULL,
    "ext" TEXT NOT NULL,
    "uploaded_by_user_id" BIGINT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "sort_order" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_issue_attachments_by_issue_id_and_image_id" ON "issue_attachments" ("issue_id", "image_id");
CREATE INDEX "index_issue_attachments_by_issue_id" ON "issue_attachments" ("issue_id");
CREATE INDEX "index_issue_attachments_by_organization_id" ON "issue_attachments" ("organization_id");
