# /var/log/vauban.log -- rotated by newsyslog(8).
# Fields: logfilename mode count size when flags [/pid_file] [sig_num]
# size is in KiB: 1048576 KiB = 1 GiB.
/var/log/vauban.log			600  20	 1048576  *     CW  /var/run/vauban.pid  1
