version = 1

[[migrations]]
id = 7227258433402660679
name = "0000_initial.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 8297320574297276907
name = "0001_issue_comments.sql"
snapshot_name = "0001_snapshot.toml"

[[migrations]]
id = 2117877316932323482
name = "0002_doc_slug_versions.sql"
snapshot_name = "0002_snapshot.toml"

[[migrations]]
id = 3093399681866925641
name = "0003_portal_role_and_release_org.sql"
snapshot_name = "0003_snapshot.toml"

[[migrations]]
id = 8821032828437798156
name = "0004_ephemeral_downloads.sql"
snapshot_name = "0004_snapshot.toml"

[[migrations]]
id = 6614829037152048591
name = "0005_release_sha256.sql"
snapshot_name = "0005_snapshot.toml"
