/// VAUBAN Web - Accounts templates.
pub mod apikey_create_form;
pub mod apikey_created;
pub mod apikey_list;
pub mod group_add_member;
pub mod group_create;
pub mod group_detail;
pub mod group_edit;
pub mod group_list;
pub mod login;
pub mod mfa_setup;
pub mod mfa_verify;
pub mod profile;
pub mod session_list;
pub mod user_create;
pub mod user_detail;
pub mod user_edit;
pub mod user_list;

pub use apikey_create_form::ApikeyCreateFormTemplate;
pub use apikey_created::ApikeyCreatedTemplate;
pub use apikey_list::{ApiKeyItem, ApikeyListTemplate};
pub use group_add_member::{AvailableUser, GroupAddMemberTemplate, GroupInfo};
pub use group_create::GroupCreateTemplate;
pub use group_detail::GroupDetailTemplate;
pub use group_edit::{GroupEditData, GroupEditTemplate};
pub use group_list::GroupListTemplate;
pub use login::LoginTemplate;
pub use mfa_setup::MfaSetupTemplate;
pub use mfa_verify::MfaVerifyTemplate;
pub use profile::{ProfileDetail, ProfileSession, ProfileTemplate};
pub use session_list::{AuthSessionItem, SessionListTemplate};
pub use user_create::UserCreateTemplate;
pub use user_detail::{UserDetail, UserDetailTemplate};
pub use user_edit::{UserEditData, UserEditTemplate};
pub use user_list::{Pagination, UserListTemplate};
