#!/usr/bin/env bash
#
# VAU-008 (ephemeral) lint: the MFA setup GET handlers must be side-effect free,
# the TOTP candidate may only be (re)generated by the CSRF-gated POST
# `mfa_setup_init` (no password at first enrolment, current-TOTP step-up for
# rotation), and the candidate must live ONLY in the per-session in-memory
# store -- never in `users`. Mirrors `tests/security/mfa_setup_invariants_test.rs`
# so a regression is caught before `cargo test`.
#
# Usage: bash vauban-web/scripts/check_mfa_setup_no_get_side_effect.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CRATE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
AUTH="${CRATE_DIR}/src/handlers/auth.rs"
USERS="${CRATE_DIR}/src/handlers/web/users.rs"
MAIN="${CRATE_DIR}/src/main.rs"

status=0

# Print the body of a single function: from the start marker up to (but not
# including) the next `async fn ` boundary.
extract_fn() {
    local file="$1" marker="$2"
    awk -v marker="$marker" '
        index($0, marker) { grab=1; print; next }
        grab && / fn [a-zA-Z_]+\(/ { exit }
        grab { print }
    ' "$file"
}

fail() {
    echo "FAIL (VAU-008): $1" >&2
    status=1
}

# INV-1: GET handlers must not write to the DB or the candidate store.
for spec in \
    "${AUTH}:::pub async fn mfa_setup_page(" \
    "${USERS}:::pub async fn mfa_setup("; do
    file="${spec%%:::*}"
    marker="${spec##*:::}"
    body="$(extract_fn "${file}" "${marker}")"
    if grep -qE 'diesel::update|diesel::insert_into' <<<"${body}"; then
        fail "${marker%(*} performs a DB write (INV-1: GET must be read-only)."
    fi
    if grep -qE '\.put\(' <<<"${body}"; then
        fail "${marker%(*} writes to the candidate store (INV-1: GET must be read-only)."
    fi
    # INV-2: GET handlers must not generate a secret.
    if grep -qE 'mfa_generate|generate_totp_secret' <<<"${body}"; then
        fail "${marker%(*} generates a TOTP secret (INV-2: only mfa_setup_init may)."
    fi
done

# INV-1: the persisted candidate column is fully retired from the handlers.
for file in "${AUTH}" "${USERS}"; do
    if grep -q 'pending_mfa_secret' "${file}"; then
        fail "${file##*/} still references the retired pending_mfa_secret column (INV-1)."
    fi
done

# INV-2/INV-3 (positive): init is CSRF-gated, password-free, verifies the
# current TOTP (rotation step-up), and is the generator.
init_body="$(extract_fn "${AUTH}" "pub async fn mfa_setup_init(")"
grep -q 'validate_double_submit' <<<"${init_body}" || fail "mfa_setup_init lacks CSRF validation (INV-2)."
if grep -q 'verify_password' <<<"${init_body}"; then
    fail "mfa_setup_init must NOT ask for a password (first enrolment is password-free) (INV-3)."
fi
grep -q 'verify_totp' <<<"${init_body}" || fail "mfa_setup_init lacks the current-TOTP rotation step-up (INV-3)."
grep -qE 'mfa_generate|generate_totp_secret' <<<"${init_body}" || fail "mfa_setup_init does not generate the secret (INV-2)."

# INV-1: init stores ONLY in the in-memory store; confirm promotes mfa_secret,
# reads the candidate from the store and evicts it.
# (the store call spans multiple lines, so check the marker and the verb
# independently rather than on a single line).
grep -q 'pending_mfa' <<<"${init_body}" && grep -qE '\.put\(' <<<"${init_body}" \
    || fail "mfa_setup_init does not store the candidate in the in-memory store (INV-1)."
if grep -q 'users::mfa_secret.eq(' <<<"${init_body}"; then
    fail "mfa_setup_init writes mfa_secret directly (INV-1: candidate stays in memory)."
fi
confirm_body="$(extract_fn "${AUTH}" "pub async fn mfa_setup_submit(")"
grep -q 'users::mfa_secret.eq(' <<<"${confirm_body}" || fail "mfa_setup_submit does not promote mfa_secret (INV-1)."
grep -q 'pending_mfa' <<<"${confirm_body}" && grep -qE '\.get\(' <<<"${confirm_body}" \
    || fail "mfa_setup_submit does not read the candidate from the store (INV-1)."
grep -qE '\.evict\(' <<<"${confirm_body}" || fail "mfa_setup_submit does not evict the candidate after enrolment (INV-1)."

# INV-4: audit + routing.
grep -q 'AuditEventType::MfaSecretGenerated' <<<"${init_body}" || fail "mfa_setup_init does not emit MfaSecretGenerated (INV-4)."
if ! grep -q '/mfa/setup/init' "${MAIN}"; then
    fail "POST /mfa/setup/init is not routed in main.rs."
fi

if [[ "${status}" -eq 0 ]]; then
    echo "OK: GET /mfa/setup is side-effect free; generation is gated by CSRF + step-up (VAU-008)."
fi

exit "${status}"
