#!/usr/bin/env bash
#
# VAU-008 lint: the MFA setup GET handlers must be side-effect free, and the
# TOTP secret may only be (re)generated by the CSRF + password step-up POST
# `mfa_setup_init`. Mirrors `tests/security/mfa_setup_invariants_test.rs` so a
# regression is caught before `cargo test`.
#
# Usage: bash vauban-web/scripts/check_mfa_setup_no_get_side_effect.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CRATE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
AUTH="${CRATE_DIR}/src/handlers/auth.rs"
USERS="${CRATE_DIR}/src/handlers/web/users.rs"
MAIN="${CRATE_DIR}/src/main.rs"

status=0

# Print the body of a single function: from the start marker up to (but not
# including) the next `async fn ` boundary.
extract_fn() {
    local file="$1" marker="$2"
    awk -v marker="$marker" '
        index($0, marker) { grab=1; print; next }
        grab && / fn [a-zA-Z_]+\(/ { exit }
        grab { print }
    ' "$file"
}

fail() {
    echo "FAIL (VAU-008): $1" >&2
    status=1
}

# INV-1: GET handlers must not write to the DB.
for spec in \
    "${AUTH}:::pub async fn mfa_setup_page(" \
    "${USERS}:::pub async fn mfa_setup("; do
    file="${spec%%:::*}"
    marker="${spec##*:::}"
    body="$(extract_fn "${file}" "${marker}")"
    if grep -qE 'diesel::update|diesel::insert_into' <<<"${body}"; then
        fail "${marker%(*} performs a DB write (INV-1: GET must be read-only)."
    fi
    # INV-2: GET handlers must not generate a secret.
    if grep -qE 'mfa_generate|generate_totp_secret' <<<"${body}"; then
        fail "${marker%(*} generates a TOTP secret (INV-2: only mfa_setup_init may)."
    fi
done

# INV-2 (positive): init enforces CSRF + password step-up and is the generator.
init_body="$(extract_fn "${AUTH}" "pub async fn mfa_setup_init(")"
grep -q 'validate_double_submit' <<<"${init_body}" || fail "mfa_setup_init lacks CSRF validation (INV-2)."
grep -q 'verify_password' <<<"${init_body}" || fail "mfa_setup_init lacks the password step-up (INV-2)."
grep -qE 'mfa_generate|generate_totp_secret' <<<"${init_body}" || fail "mfa_setup_init does not generate the secret (INV-2)."

# INV-3: init writes ONLY pending; confirm promotes mfa_secret and clears pending.
grep -q 'pending_mfa_secret.eq(' <<<"${init_body}" || fail "mfa_setup_init does not write pending_mfa_secret (INV-3)."
if grep -q 'users::mfa_secret.eq(' <<<"${init_body}"; then
    fail "mfa_setup_init writes mfa_secret directly (INV-3: only pending allowed)."
fi
confirm_body="$(extract_fn "${AUTH}" "pub async fn mfa_setup_submit(")"
grep -q 'users::mfa_secret.eq(' <<<"${confirm_body}" || fail "mfa_setup_submit does not promote mfa_secret (INV-3)."
grep -q 'pending_mfa_secret.eq(None' <<<"${confirm_body}" || fail "mfa_setup_submit does not clear pending (INV-3)."

# INV-4: audit + routing.
grep -q 'AuditEventType::MfaSecretGenerated' <<<"${init_body}" || fail "mfa_setup_init does not emit MfaSecretGenerated (INV-4)."
if ! grep -q '/mfa/setup/init' "${MAIN}"; then
    fail "POST /mfa/setup/init is not routed in main.rs."
fi

if [[ "${status}" -eq 0 ]]; then
    echo "OK: GET /mfa/setup is side-effect free; generation is gated by CSRF + step-up (VAU-008)."
fi

exit "${status}"
